GTA terminadaa
ify/delete): .DS_Store deleted in HEAD and modified in 5fad431 (GTA terminadaa).  Version 5fad431 (GTA terminadaa) of .DS_Store left in tree.
error: could not apply 5fad431... GTA terminadaa
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 5fad431... # GTA terminadaa
catalinavalbuena@MacBook-Air-de-Catalina Actividad_1 % git rm .DS_Store
rm '.DS_Store'
catalinavalbuena@MacBook-Air-de-Catalina Actividad_1 % git add .
catalinavalbuena@MacBook-Air-de-Catalina Actividad_1 % git rebase --continue
hint: Waiting for your editor to close the file...
GTA terminadaa

~
~
~
~
~
~
~
~
~
"~/Desktop/Actividad_1/.git/COMMIT_EDITMSG" 20L, 637B    #